openapi: 3.0.3
paths:
  /students:
    get:
      summary: Get all students
      description: Returns a paginated list of students
      parameters:
        - name: cursor
          in: query
          required: false
          schema:
            type: string
          description: Cursor for pagination
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Number of items to return
      responses:
        "200":
          description: Paginated list of students
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudentListResponse"
  /students/{studentId}:
    get:
      summary: Get student by ID
      description: Returns a single student
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Student details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Student"
        "404":
          description: Student not found
  /positions:
    get:
      summary: Get all positions
      description: Returns a paginated list of positions
      parameters:
        - name: cursor
          in: query
          required: false
          schema:
            type: string
          description: Cursor for pagination
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Number of items to return
      responses:
        "200":
          description: Paginated list of positions
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PositionListResponse"
  /positions/{positionId}:
    get:
      summary: Get position by ID
      description: Returns a single position
      parameters:
        - name: positionId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Position details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Position"
        "404":
          description: Position not found
  /highSchool:
    get:
      summary: Get all high schools
      description: Returns a paginated list of high schools
      parameters:
        - name: cursor
          in: query
          required: false
          schema:
            type: string
          description: Cursor for pagination
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Number of items to return
      responses:
        "200":
          description: Paginated list of high schools
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HighSchoolListResponse"
  /highSchool/{highSchoolId}:
    get:
      summary: Get high school by ID
      description: Returns a single high school
      parameters:
        - name: highSchoolId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: High school details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HighSchool"
        "404":
          description: Position not found
components:
  schemas:
    StudentListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Student"
        nextCursor:
          type: string
          nullable: false
          description: Cursor for next page, or null if no more results
    PositionListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Position"
        nextCursor:
          type: string
          nullable: false
          description: Cursor for next page, or null if no more results
    HighSchoolListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/HighSchool"
        nextCursor:
          type: string
          nullable: false
          description: Cursor for next page, or null if no more results
    Student:
      type: object
      required:
        - firstName
        - lastName
        - graduationYear
        - email
        - phone
        - homeAddress
        - schoolAddress
        - schoolName
      properties:
        firstName:
          type: string
        lastName:
          type: string
        graduationYear:
          type: integer
        email:
          type: string
          format: email
        phone:
          type: string
        homeAddress:
          type: string
        schoolAddress:
          type: string
        schoolName:
          type: string
    Position:
      type: object
      required:
        - id
        - company
        - status
        - address
      properties:
        id:
          type: string
          format: uuid
        company:
          type: string
        address:
          type: string
        remote:
          type: boolean
          description: Indicates if the position is remote
        startDate:
          type: string
          format: date
          nullable: true
        endDate:
          type: string
          format: date
          nullable: true
        status:
          type: string
          enum:
            - active
            - inactive
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    HighSchool:
      type: object
      required:
        - name
        - gwLocation
        - address
      properties:
        id:
          type: string
          format: uuid
          x-faker: string.uuid
        gwLocation:
          type: string
          x-faker: address.cityName
        address:
          type: string
          x-faker: address.streetAddress
