/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all students
         * @description Returns a paginated list of students
         */
        get: {
            parameters: {
                query?: {
                    /** @description Cursor for pagination */
                    cursor?: string;
                    /** @description Number of items to return */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of students */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get student by ID
         * @description Returns a single student
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    studentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Student details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Student"];
                    };
                };
                /** @description Student not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all placements
         * @description Returns a paginated list of placements
         */
        get: {
            parameters: {
                query?: {
                    /** @description Cursor for pagination */
                    cursor?: string;
                    /** @description Number of items to return */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of placements */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlacementListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/placements/{placementId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get placement by ID
         * @description Returns a single placement
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    placementId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Placement details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Placement"];
                    };
                };
                /** @description Placement not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StudentListResponse: {
            items?: components["schemas"]["Student"][];
            /** @description Cursor for next page, or null if no more results */
            nextCursor?: string | null;
        };
        PlacementListResponse: {
            items?: components["schemas"]["Placement"][];
            /** @description Cursor for next page, or null if no more results */
            nextCursor?: string | null;
        };
        Student: {
            firstName: string;
            lastName: string;
            graduationYear: number;
            /** Format: email */
            email: string;
            phone: string;
            homeAddress: string;
            schoolAddress: string;
            schoolName: string;
        };
        Placement: {
            /** Format: uuid */
            id: string;
            company: string;
            address: string;
            /** @description Indicates if the placement is remote */
            remote?: boolean;
            /** Format: date */
            startDate?: string | null;
            /** Format: date */
            endDate?: string | null;
            /** @enum {string} */
            status: "active" | "inactive";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
